version: "3.9"
services:
  esurvey-service:
    container_name: esurvey-service
    image: "esurvey-service:latest"
    restart: always
    environment:
      TZ: "Asia/Jakarta"
      PORT: "7002"
      JWT_SECRET: "3SurveyBp1"
      JWT_EXPIRATION: "24h"
      DB_HOST: mysql5
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "bpikemendesa123!#"
      DB_DATABASE: "esurvey"
    ports:
      - "127.0.0.1:7002:7002"
    networks:
      - bpi_network

networks:
  bpi_network:
    external: true
