version: "3.9"
services:
  esurvey-service:
    container_name: esurvey-service
    image: "esurvey-service:latest"
    restart: always
    environment:
      TZ: "Asia/Jakarta"
      PORT: "7002"
      JWT_SECRET: "3SurveyBp1"
      JWT_EXPIRATION: "24h"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "mujahid212"
      DB_DATABASE: "esurvey"
    ports:
      - "127.0.0.1:7002:7002"
    networks:
      - matik_network

networks:
  matik_network:
    external: true
